### ISSUE TITLE
Do we really need the hard setuptools pin?

### ISSUE THREAD

**Issue by izahn** [conda-forge/celery-feedstock#68]
### Comment:

@AdannaVardian I see that you hard pinned `setuptools` in https://github.com/conda-forge/celery-feedstock/blob/20b417c43b5f19b9c3076420ae611aebdb38189d/recipe/meta.yaml#L34 . Is that really needed? 

More generally @conda-forge/celery is `setuptools` needed as a runtime dependency at all? `grayskull pypi celery ` doesn't think it needs `setuptools` at all.

**Comment by chrisburr** [comment]
It seems it was intentional for that version: https://github.com/celery/celery/blob/a31d6f45334ef8d9df93cae78338dabc81028b5b/Changelog.rst#523

And it was removed for v5.2.5: https://github.com/celery/celery/commit/20d88756ab9d9b62748193af048f17f91f7a9261

@izahn Would you be able to open a PR to fix it?
